use_frameworks!

platform :ios, '12.4'

target 'UIKitDOM_Example' do
  pod 'UIKitDOM', :path => '../'

  target 'UIKitDOM_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end
